import { Aggiunta } from './aggiunte';

export class AggiunteService {
  
  getAll() : Aggiunta[] {
    return [
      
      {nome:"pomodoro",prezzo:0.50},
      {nome:"mozzarella",prezzo:1},
      {nome:"burrata",prezzo:2.50},
      {nome:"bufala",prezzo:1.60},
      {nome:"patate viola",prezzo:1.60},
      {nome:"patate",prezzo:1},
      {nome:"wurstel",prezzo:1},
      {nome:"salamino",prezzo:1},
      {nome:"tonno",prezzo:1},
      {nome:"cipolla",prezzo:1},
      {nome:"cotto",prezzo:1},
      {nome:"speck",prezzo:1.60},
      {nome:"sauris",prezzo:1.60},
      {nome:"crudo",prezzo:1.60},
      {nome:"pancetta arrotolata",prezzo:1.60},
      {nome:"pancetta affumicata",prezzo:1.60},
      {nome:"lardo",prezzo:1.60},
      {nome:"guanciale",prezzo:1.60},
      {nome:"philadelphia",prezzo:1.60},
      {nome:"gorgonzola",prezzo:1.60},
      {nome:"emmenthal",prezzo:1.60},
      {nome:"asiago",prezzo:1.60},
      {nome:"pecorino",prezzo:1.60},
      {nome:"grana",prezzo:1.60},
      {nome:"uovo",prezzo:1},
      {nome:"chiodini",prezzo:1.60},
      {nome:"porcini",prezzo:1.60},
      {nome:"funghi",prezzo:1},
      {nome:"tartufo",prezzo:1.60},
      {nome:"melanzane",prezzo:1},
      {nome:"zucchine",prezzo:1},
      {nome:"peperoni",prezzo:1},
      {nome:"capperi",prezzo:1},
      {nome:"acciughe",prezzo:1},
      {nome:"olio aglio",prezzo:0.50},
      {nome:"tastasal",prezzo:1},
      {nome:"gamberetti",prezzo:1.60},
      {nome:"rosmarino",prezzo:0.50},
      {nome:"origano",prezzo:0.50},
      {nome:"angus",prezzo:1.60},
      {nome:"rucola",prezzo:1},
      {nome:"stracchino",prezzo:1.60},
      {nome:"ricotta",prezzo:1.60},
      {nome:"panna",prezzo:1},
      {nome:"olive taggiasche",prezzo:1},
      {nome:"salmone",prezzo:1.60},
      {nome:"gratinato",prezzo:1.60},
      {nome:"dadolata",prezzo:1.60},
      {nome:"cirio",prezzo:1},
      {nome:"confit",prezzo:1.60},
      {nome:"cantabrico",prezzo:1.60},
      {nome:"friarielli",prezzo:1.60},
      {nome:"frutti del cappero",prezzo:1.60},
      {nome:"olive denocciolate",prezzo:1},
      {nome:"frutti di mare",prezzo:1.60},
      {nome:"circe",prezzo:1.60},
      {nome:"funghi freschi",prezzo:1},
      {nome:"spinaci",prezzo:1},
      {nome:"misto bosco",prezzo:1.60},
      {nome:"brie",prezzo:1.60},
      {nome:"scamorza",prezzo:1.60},
      {nome:"bresaola",prezzo:1.60},
      {nome:"rucola",prezzo:1},
      {nome:"fagioli",prezzo:1},
      {nome:"radicchio",prezzo:1},
      {nome:"treviso",prezzo:1.60},
      {nome:"feta greca",prezzo:1.60},
      {nome:"crema d'asparagi",prezzo:1.60},
      {nome:"pistacchi",prezzo:1.60},
      {nome:"pesto",prezzo:1.60},
      {nome:"aneto",prezzo:1},
      {nome:"rape",prezzo:1.60},
      {nome:"anatra",prezzo:1.60},
      {nome:"noci",prezzo:1.60},
      {nome:"pepe",prezzo:0.50},
      {nome:"peperoncino",prezzo:0.50},
      {nome:"peperoncino dolce",prezzo:0.50},
      {nome:"menta",prezzo:0.50},
      {nome:"amarone",prezzo:1},
      {nome:"misticanza",prezzo:1},
      {nome:"aceto balsamico",prezzo:1},
      {nome:"miele",prezzo:1},
      {nome:"fiori",prezzo:1},
      {nome:"pere",prezzo:1.60},
      {nome:"semi di papavero",prezzo:1},
      {nome:"marmellata d'arancia",prezzo:1},
      {nome:"erba cipollina",prezzo:1},
      {nome:"nduia",prezzo:1.60}
      
      
    ];
  }

}
